---
- name: Verify
  hosts: all
  gather_facts: false
  become: true

  vars:
      role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"

  tasks:
      - name: "Include verify tasks"
        ansible.builtin.include_role:
            name: "{{ role_name }}"
            tasks_from: verify
