- hosts: "{{ hosts }}"
  become: true
  become_user: root
  gather_facts: true
  tasks:
   - name: Remove Password For SSH User "{{ user }}"
     user: 
        name: "{{ user }}"
        update_password: always
        password: "!!"
        state: present
