- hosts: "{{hosts}}"
  become: true
  become_user: root
  gather_facts: yes
  tasks:
    - name: comment old conf
      replace:
        dest: /etc/rsyslog.conf
        regexp: '^(?!#)(.*@10.*)'
        replace: '#\1'
    - name: Adding New Qradar Server To rsyslog File
      lineinfile:
        path: /etc/rsyslog.conf
        line: "*.*\t@@{{IP}}:541"
        insertafter: '"*.info"'

    - name: Restart rsyslog Service
      service:
         name: rsyslog
         state: restarted
